### ISSUE TITLE
[JOSS] unit tests failing on master

### ISSUE THREAD

**Issue by zonca** [Jammy2211/PyAutoLens#146]
JOSS review: https://github.com/openjournals/joss-reviews/issues/2825

I am trying to run unit tests on the current master branch with `pytest`,
I see all the plotting tests failing plus another 2.
I tested `welcome.py` from the `autolens_workspace` and there plotting works fine.

Do I need to configure plotting specifically to run the tests?
Or is `master` currently broken and I should try another version?

I attach test `pytest` logs:
[pyautolens_pytest.log](https://github.com/Jammy2211/PyAutoLens/files/5521241/pyautolens_pytest.log)

And the packages in the conda env I'm using:
[environment.txt](https://github.com/Jammy2211/PyAutoLens/files/5521259/environment.txt)

**Comment by Jammy2211** [comment]
The failing tests are due to my poor handling of path construction and is actually on my to do list to fix in the next few days :). We're actually about to make autolens Windows compatbible which these tests would not play nice with at all, so need to switch everything to pathlib (should of been doing this all along but got lazy).

As you say, this shouldn't impact the actual code performance for you as the tests are failing because they're making assertions on the path string structure. I'll let you know once we've got this sorted.
