### ISSUE TITLE
Coordinate Convention

### ISSUE THREAD

**Issue by rhayes777** [Jammy2211/PyAutoLens#28]
In computer imagery (0, 0) generally refers to the top left point in an image.

In the image module we are using the convention that the central image pixel has arcsecond coordinates of (0, 0) with the (0, 0) pixel coordinates being negative x and y. This implicitly assumes that images defined in arcseconds use the same convention as computer imagery. It is worth being aware of this assumption as it may cause results to be rotated from what we would expect them to be.

**Comment by rhayes777** [comment]
It seems that output images are rotated when compared to the image that they are fitting

**Comment by Jammy2211** [comment]
I have implemented a flipud(image.T) in all visualizations, to correct the output image flip.

 It is because our coordinate was defined as:

```
np.array([[[-1., -1.], [-1., 0.], [-1., 1.]],
                    [[0., -1.], [0., 0.], [0., 1.]],
                     [[1., -1.], [1., 0.], [1., 1.]]])
```

Where the y-coordinates run from negative-to-positive downwards, instead of upwards.

Im not gonna close as im not 100% the solution I implemented wont bite us in the arse.
