### ISSUE TITLE
apply_function and map_function in ImagingGrids don't pass class attributes

### ISSUE THREAD

**Issue by Jammy2211** [Jammy2211/PyAutoLens#48]
These two functions don't pass the non-grid attrbutes (e.g. the mask) to new ImagingGrids setup during ray_tracing. These attributes must be passed for visualization.

In ray tracing... you can see I've made a prertty nasty hack to fix this for now. If you could fix these two functions then we'll have neat tidy code again!

**Comment by rhayes777** [comment]
I used __array_finalize__ correctly in Grid classes to pass missing attributes and integrated this into the planes module. It seems to have fixed the issue; note that __array_finalize__ must be updated when classes inheriting from image grid are changed so that they apply and map functions work as expected.
